spring:
  application:
    name: technicalchallenge
  datasource:
    url: jdbc:mysql://localhost:3306/alura
    username: dbuser
    password: user@123
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    url: jdbc:mysql://localhost:3306/alura
    user: dbuser
    password: user@123
    locations: classpath:db/migration