CREATE TABLE user (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  username VARCHAR(20) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role ENUM('ESTUDANTE', 'INSTRUTOR', 'ADMIN') NOT NULL,
  creation_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
